In [36]:
import torch
import pickle
import numpy as np

In [28]:
with open('points.pickle', 'rb') as handle:
    points = pickle.load(handle)
with open('box.pickle', 'rb') as handle:
    box = pickle.load(handle)

In [37]:
with open('pred_dicts0.pickle', 'rb') as handle:
    pred_dict = pickle.load(handle)

In [38]:
pred_dict.keys()

dict_keys(['pred_boxes', 'pred_scores', 'pred_labels'])

In [34]:
pred_dict['pred_labels']

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
pred_dict['pred_scores']

tensor([0.6139, 0.4585, 0.3431, 0.3146, 0.2737, 0.2608, 0.2360, 0.2321, 0.2233,
        0.2134, 0.2090, 0.2034, 0.1535, 0.1509, 0.1429, 0.1281, 0.1267, 0.1105,
        0.1083, 0.1040, 0.1035, 0.1000])

In [33]:
pred_dict['pred_scores']

tensor([0.6139, 0.4585, 0.3431, 0.3146, 0.2737, 0.2608, 0.2360, 0.2321, 0.2233,
        0.2134, 0.2090, 0.2034, 0.1535, 0.1509, 0.1429, 0.1281, 0.1267, 0.1105,
        0.1083, 0.1040, 0.1035, 0.1000])

In [30]:
original_points = np.load('0038_flip_x.npy')
original_points

array([[-0.      , -0.      ,  0.      ,  0.      ],
       [-0.      , -0.      ,  0.      ,  0.      ],
       [-0.      ,  0.      ,  0.      ,  0.      ],
       ...,
       [-1.017862, -0.014363, -0.284604,  0.      ],
       [-1.002319,  0.023648, -0.291092,  0.      ],
       [-0.      ,  0.      , -0.      ,  0.      ]])

In [31]:
points

tensor([[-0., -0., 0., 0.],
        [-0., -0., 0., 0.],
        [-0., 0., 0., 0.],
        ...,
        [-0., 0., -0., 0.],
        [-0., -0., -0., 0.],
        [-0., 0., -0., 0.]])

In [32]:
box

tensor([[ 1.2031e+01,  1.2332e+01, -2.4059e-01,  4.2214e+00,  1.6851e+00,
          1.5094e+00,  2.6132e+00],
        [ 4.0784e+01, -8.5878e+00,  4.6468e-01,  3.8367e+00,  1.6026e+00,
          1.4607e+00,  2.6140e+00],
        [ 2.8868e+01,  2.7534e+00,  5.0707e-01,  4.0162e+00,  1.6076e+00,
          1.5282e+00,  1.6533e+00],
        [ 4.6299e+01,  6.2338e+00,  8.1870e-01,  4.2639e+00,  1.6388e+00,
          1.5250e+00,  1.6065e+00],
        [ 3.1360e+01, -1.1791e-01,  5.2009e-01,  3.9506e+00,  1.6822e+00,
          1.5831e+00,  2.8671e+00],
        [ 2.6353e+01, -2.7161e+01,  2.7408e-01,  4.1263e+00,  1.6747e+00,
          1.6123e+00,  5.7913e+00],
        [ 2.1549e+01, -2.8780e+01, -1.9644e-01,  3.8173e+00,  1.4608e+00,
          1.4021e+00,  2.7826e+00],
        [ 1.5247e+01, -4.0475e+01, -5.3947e-02,  3.9479e+00,  1.6202e+00,
          1.5303e+00,  2.3432e+00],
        [ 1.8428e+01, -3.4142e+01,  8.7303e-03,  4.1846e+00,  1.6629e+00,
          1.5222e+00,  1.0314e+00],
        [ 